/*
 * Copyright (c) Cross-Engine Editor Project.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 */

#pragma once

//! ActionManager bootstrap for the CEE shell (editor_polish.md P0-4 / P1-12 / P1-13).
//!
//! The whole menu bar is generated by the ActionManager, like the native editor: this handler
//! registers the action context, the menu bar (File/Edit/Tools/View/Help with the framework's
//! o3de.menu.editor.* ids; Game reserved at sortkey 300 for ISimulation per D2), every CEE
//! action (cee.action.*, D2b) and the three context menus. It mirrors the native
//! EditorActionsHandler's hook structure minus the Atom-bound EditorLib parts (no prefab
//! actions - D7, no placeholder slots - S3). Engine-specific actions arrive through the
//! backend seam (P1-13 / M1) - a new engine never touches this file.

#include <AzCore/std/functional.h>
#include <AzCore/std/string/string.h>

#include <AzToolsFramework/ActionManager/ActionManagerRegistrationNotificationBus.h>
#include <AzToolsFramework/API/ToolsApplicationAPI.h>

namespace AzToolsFramework
{
    class ActionManagerInterface;
    class HotKeyManagerInterface;
    class MenuManagerInterface;
}

namespace CrossEngineEditor
{
    class EditorMainWindow;

    class CeeActionsHandler final
        : private AzToolsFramework::ActionManagerRegistrationNotificationBus::Handler
        , private AzToolsFramework::ToolsApplicationNotificationBus::Handler
    {
    public:
        explicit CeeActionsHandler(EditorMainWindow* mainWindow);
        ~CeeActionsHandler() override;

    private:
        // AzToolsFramework::ActionManagerRegistrationNotificationBus::Handler...
        void OnActionContextRegistrationHook() override;
        void OnActionUpdaterRegistrationHook() override;
        void OnActionRegistrationHook() override;
        void OnMenuBarRegistrationHook() override;
        void OnMenuRegistrationHook() override;
        void OnMenuBindingHook() override;
        void OnPostActionManagerRegistrationHook() override;

        // AzToolsFramework::ToolsApplicationNotificationBus::Handler...
        //! Keep the selection-sensitive entries' enable state honest (尺子2).
        void AfterEntitySelectionChanged(
            const AzToolsFramework::EntityIdList& newlySelectedEntities,
            const AzToolsFramework::EntityIdList& newlyDeselectedEntities) override;

        //! Register one action in the main-window context that delegates to a main-window
        //! operation (the single source of truth - the same path every menu uses).
        void RegisterMainWindowAction(
            const char* actionIdentifier, const char* name, const char* description, AZStd::function<void()> operation,
            const char* hotKey = nullptr);
        //! Selection-sensitive variant: also installs the enabled-state callback and adds the
        //! action to the selection updater.
        void RegisterSelectionSensitiveAction(
            const char* actionIdentifier, const char* name, const char* description, AZStd::function<void()> operation,
            const char* hotKey = nullptr);
        //! Checkable action variant (used for the View-menu panel toggles).
        void RegisterCheckableAction(
            const char* actionIdentifier, const char* name, AZStd::function<void()> handler,
            AZStd::function<bool()> checkState, int menuSortKey, const AZStd::string& menuId);

        //! True when at least one entity is selected (enable state for the edit pool).
        static bool AnyEntitySelected();

        EditorMainWindow* m_mainWindow = nullptr;

        AzToolsFramework::ActionManagerInterface* m_actionManagerInterface = nullptr;
        AzToolsFramework::HotKeyManagerInterface* m_hotKeyManagerInterface = nullptr;
        AzToolsFramework::MenuManagerInterface* m_menuManagerInterface = nullptr;
    };
} // namespace CrossEngineEditor
