/*
 * Copyright (c) Cross-Engine Editor Project.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 */

#pragma once

#if !defined(Q_MOC_RUN)
#include <Window/ViewPaneRegistry.h>

#include <MaterialEditor/Vendor/AtomToolsFramework/Document/AtomToolsDocumentInspector.h>
#include <MaterialEditor/Vendor/AtomToolsFramework/Document/AtomToolsDocumentNotificationBus.h>
#include <MaterialEditor/CeeMaterialDocumentInspector.h>

#include <AzCore/Component/EntityId.h>
#include <AzCore/std/containers/vector.h>
#include <AzCore/std/smart_ptr/unique_ptr.h>

#include <AzFramework/Viewport/ViewportId.h>

#include <AzQtComponents/Components/DockMainWindow.h>

#include <AzToolsFramework/Entity/EntityTypes.h>
#endif

class QCloseEvent;
class QLabel;
class QMenu;
class QTimer;

namespace AzToolsFramework
{
    class EntityPropertyEditor;
    class ToastNotificationsView;
    class TreeViewState;
}

namespace AzQtComponents
{
    class SegmentControl;
    enum class ToastType : int;
}

namespace ads
{
    class CDockManager;
    class CDockWidget;
} // namespace ads

namespace CrossEngineEditor
{
    class CeeMaterialDocument;
    class CeeMaterialPreviewPanel;
    class CeeMaterialToolbar;
    class CeePreferences;
    class EditorViewportWidget;
    class EntityMirrorBridge;

    //! Single editor viewport id shared by the viewport widget and the interaction system.
    inline constexpr AzFramework::ViewportId k_viewportId = 0;

    //! Thin docking main window for the cross-engine editor (Plan §B1).
    //!
    //! Hosts the reused AzToolsFramework widgets (EntityOutliner / EntityPropertyEditor /
    //! AssetBrowser), the engine viewport, the command palette and the workspace save/restore
    //! (Plan §B5). Docking is ADS-only (dock_style_review.md ch.3-1).
    //!
    //! Since editor_polish.md P1-12 the menu bar is GENERATED by the ActionManager
    //! (CeeActionsHandler registers and binds everything); this class only builds the panels
    //! (through the ViewPane registry), the viewport header bar, the main toolbar, the status
    //! bar and the toast host, and owns the workflow operations every menu delegates to.
    class EditorMainWindow
        : public AzQtComponents::DockMainWindow
        , public AtomToolsFramework::AtomToolsDocumentNotificationBus::Handler
    {
        Q_OBJECT
    public:
        //! The mirror bridge is the shell's engine <-> editor object sync (used by the
        //! create/delete UI to trigger full re-mirroring after engine-side object changes).
        explicit EditorMainWindow(EntityMirrorBridge* mirrorBridge, QWidget* parent = nullptr);
        ~EditorMainWindow() override;

        //! Bring a pane to the front (BrowseForAssets wiring and the Tools menu both land here).
        void OpenViewPane(const QString& paneName);
        //! Legacy alias for the Asset Browser pane (rbfx_migration.md §2.8).
        void ShowAssetBrowser();

        //! Dock panel state, addressed by the stable dock object name (the registry key).
        //! Read/write go straight to the docking system - it stays the only source of truth
        //! for which panels exist and whether they are open (editor_polish.md A1).
        [[nodiscard]] bool IsPanelOpen(const QString& dockName) const;
        void SetPanelOpen(const QString& dockName, bool open);

        //! The pane content widget docked under the given dock name, or null.
        [[nodiscard]] QWidget* DockContent(const QString& dockName) const;

        // ----- Engine-semantic entity operations (single source of truth) ------------------
        // editor_polish.md P0-3/P0-5: the ActionManager actions (menus / context menus /
        // shortcuts via CeeActionsHandler) and the EditorRequests bus contract all delegate to
        // these same methods, so there is exactly one backend path per operation.

        //! Create an empty engine node (root level) through the mirror contract and re-sync.
        //! Returns the mirror id the backend handed back (rbfx deliberately returns an invalid id;
        //! the real mirror entity appears after the re-sync).
        AZ::EntityId CreateEngineEntity();
        //! Delete the selection: engine nodes destroyed first (while they still resolve), then
        //! editor-side removal, then a full re-mirror so ghosts disappear.
        void DeleteSelection();
        //! Blender-style duplicate: serialize + paste without touching the clipboard.
        void DuplicateSelection();
        //! Cut = copy to the node clipboard, then the normal delete flow.
        void CutSelection();
        //! Copy the selection's engine serialization to the node clipboard.
        void CopySelection();
        //! Paste the node clipboard under the first selected mirror entity (else scene root).
        void PasteSelection();
        //! True when the system clipboard holds a node-clipboard payload (paste enable state).
        [[nodiscard]] static bool HasNodeClipboard();
        //! Frame the camera on the current selection (the "focus / F key" industry action).
        void FocusSelection();

        //! Pinned Inspector (editor_polish.md P0-3 / A3): open a second, locked copy of the
        //! property grid for the given entities; close it again when the editor asks us to.
        void OpenPinnedInspector(const AzToolsFramework::EntityIdSet& entities);
        void ClosePinnedInspector(AzToolsFramework::EntityPropertyEditor* editor);

        // ----- Level / editor workflow (ActionManager actions delegate here) ---------------

        void NewLevel();
        void OpenLevel();
        //! Returns false only when the user cancelled the save dialog.
        bool SaveLevel();
        void ShowCommandPalette();
        void ShowPreferences();
        void SaveWorkspace();
        void RestoreWorkspace();

        // ----- Status / scene state ----------------------------------------------------------

        //! Two-cell status bar contents (editor_polish.md P1-17): project path / backend name.
        void SetStatusInfo(const QString& projectPath, const QString& backendName);
        //! Display name of the open scene (title bar + dialogs); empty = untitled.
        void SetSceneDisplayName(const QString& sceneName);
        [[nodiscard]] bool IsSceneDirty() const
        {
            return m_sceneDirty;
        }
        void MarkSceneDirty();
        void ClearSceneDirty();

        //! Docked material preview widget kept in sync with the application readback loop.
        [[nodiscard]] CeeMaterialPreviewPanel* FindMaterialPreviewPanel() const;

        // AtomToolsDocumentNotificationBus::Handler — SetDocumentId on document open.
        void OnDocumentOpened(const AZ::Uuid& documentId) override;
        void OnDocumentModified(const AZ::Uuid& documentId) override;
        void OnDocumentCleared(const AZ::Uuid& documentId) override;

        //! Refresh the material toolbar combo from the document system's open documents.
        void RefreshMaterialToolbar();

        //! Show a toast notification in the bottom-right corner of this window.
        void ShowToast(AzQtComponents::ToastType type, const QString& title, const QString& description);

        //! Called by the application once ActionManager registration has run (P1-12): builds
        //! the main toolbar from the registered actions and wires the dynamic menu content.
        void OnActionManagerReady();

        //! Registry read by CeeActionsHandler when it registers pane/tool actions.
        [[nodiscard]] const ViewPaneRegistry& GetPaneRegistry() const
        {
            return m_paneRegistry;
        }
        [[nodiscard]] CeePreferences& GetPreferences()
        {
            return *m_preferences;
        }

    protected:
        // QWidget - standard exit flow (rbfx_migration.md §3.4 + editor_polish.md P2 dirty
        // tracking): with unsaved changes offer Save / Discard / Cancel; when clean just exit
        // (no point asking - "always ask" was the v1 stand-in for a dirty flag).
        void closeEvent(QCloseEvent* event) override;
        //! Toasts float over the window, so they must follow it around.
        void showEvent(QShowEvent* event) override;
        void resizeEvent(QResizeEvent* event) override;

    private Q_SLOTS:
        // Transform gizmo mode switching (Plan §B7, route B: self-drawn GizmoManager via
        // GizmoControlRequestBus, driven from the viewport header bar buttons).
        void OnTransformModeSelect();
        void OnTransformModeMove();
        void OnTransformModeRotate();
        void OnTransformModeScale();
        void OnTransformModeCombined();

    private:
        void BuildDockPanels();
        void BuildStatusBar();

        //! Gizmo control cluster attached to the viewport (editor_polish.md P1-18 / S1): a
        //! toolbar strip ABOVE the surface - transform modes, style, space, snap. QToolBar
        //! sibling of the render surface, not an overlay, so no §B8 B3 conflicts.
        QWidget* BuildViewportHeaderBar();

        //! Session-slot layout persistence (editor_polish.md P0-10 / A5): automatically saved on
        //! close and restored on startup, kept in its own QSettings group so it never overwrites
        //! the user's named Workspaces.
        void SaveSessionLayout();
        void RestoreSessionLayout();

        //! Fill the dynamic Create menu with the backend's EnumerateObjectTypes entries.
        //! Called from the Edit menu's aboutToShow (the backend builds its scene lazily on first
        //! surface, so this must not run at menu construction time). Since P1-12 each type is
        //! registered as a REAL ActionManager action (latched once, S3: no empty placeholder
        //! slots) inside the registered "o3de.menu.entity.create" submenu.
        void PopulateCreateMenu();

        //! Recent files (editor_polish.md P2): QSettings list of openable documents; the
        //! "Open Recent" submenu is fed by lazily registered actions (slots appear only once a
        //! recent file exists and are reused/renamed as the list changes).
        void RecordRecentFile(const QString& path);
        void SyncRecentActions();
        //! Open a recently used .prefab level by path (same load path as OpenLevel).
        void OpenRecentFile(const QString& path);

        //! Title bar = editor - scene [*dirty].
        void UpdateWindowTitle();

        //! Autosave timer slot: save the engine scene to <scene>.autosave when dirty.
        void OnAutosaveTimeout();

        //! (Re)start the autosave timer from the current preferences.
        void ApplyAutosaveSettings();

        //! Resolve the docked material preview panel widget once from the ADS layout.
        void EnsureMaterialPreviewPanel();

        //! Capture the Outliner's expansion state before a full re-mirror and restore it after
        //! (editor_polish.md P2, clears rbfx_migration.md §3.6 v2 backlog with the stock
        //! TreeViewState helper - the trees are framework-owned so they cannot be rebased onto
        //! QTreeViewWithStateSaving).
        void RefreshFromEngineKeepingState();

        //! Persist / restore the current dock layout to QSettings under a workspace name.
        void SaveWorkspaceLayout(const QString& name);
        bool RestoreWorkspaceLayout(const QString& name);

        //! Register a dock panel in the given area: wraps the content in an ads::CDockWidget
        //! and adds it to the dock manager (ADS owns the widget).
        void AddPanel(const QString& objectName, const QString& title, QWidget* content, Qt::DockWidgetArea area);

        //! Collect every QAction reachable from the generated menu bar AND the registered
        //! context menus (data source for the command palette, editor_polish.md P1-15).
        QList<QAction*> CollectCommands() const;

        //! Qt-Advanced-Docking-System manager. Owns all dock widgets and the layout state.
        //! Parented to this QMainWindow, so Qt destroys it - do not wrap in unique_ptr.
        //! Docking is ADS-only since the dock style review round (dock_style_review.md ch.3-1).
        ads::CDockManager* m_dockManager = nullptr;

        //! Engine <-> editor object sync (not owned; owned by the application, which outlives
        //! the window). Create/delete UI calls RefreshFromEngine through it.
        EntityMirrorBridge* m_mirrorBridge = nullptr;

        //! The viewport controller (owned by the dock hierarchy). FocusSelection frames it.
        EditorViewportWidget* m_viewport = nullptr;

        //! ViewPane registry (P1-14): populated once in the ctor, before registration runs.
        ViewPaneRegistry m_paneRegistry;

        //! Editor preferences (P2): reflected, SettingsRegistry-backed, shared with the dialog.
        AZStd::unique_ptr<CeePreferences> m_preferences;

        //! Open pinned-inspector windows (children of this window; Qt deletes them with it).
        AZStd::vector<QWidget*> m_pinnedInspectorWindows;

        //! Status bar cells (P1-17): project path / backend name.
        QLabel* m_statusProject = nullptr;
        QLabel* m_statusBackend = nullptr;

        //! Main toolbar (P1-16), built from registered actions in OnActionManagerReady.
        QToolBar* m_mainToolBar = nullptr;

        //! Toast host (P2): bottom-right notifications, addressed on ToastRequestBus.
        AzToolsFramework::ToastNotificationsView* m_toastView = nullptr;

        //! Autosave (P2): periodic save of the engine scene while dirty.
        QTimer* m_autosaveTimer = nullptr;
        QString m_sceneDisplayName;
        bool m_sceneDirty = false;

        //! Docked material preview panel resolved once from ADS on first use.
        CeeMaterialPreviewPanel* m_materialPreviewPanel = nullptr;
        CeeMaterialDocumentInspector* m_materialInspector = nullptr;

        //! Active material document currently bound to the inspector/preview.
        AZ::Uuid m_activeDocumentId;

        //! Material toolbar combo for open documents (task 2).
        CeeMaterialToolbar* m_materialToolbar = nullptr;

        //! Outliner expansion snapshot for RefreshFromEngineKeepingState.
        AZStd::unique_ptr<AzToolsFramework::TreeViewState> m_outlinerTreeState;

        //! True once the dynamic Create menu has been filled from EnumerateObjectTypes.
        bool m_createMenuPopulated = false;
    };
} // namespace CrossEngineEditor
